In [1]:
import pandas as pd

In [2]:
# import dataset
df = pd.read_csv("Uncleaned_employees_final_dataset (1).csv")

In [3]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,NaN,1,1,0,77
1,74430,HR,region_4,Bachelors,f,other,1,31,3.0,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.0,4,0,0,47
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.0,9,0,0,65
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.0,7,0,0,61

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17417 entries, 0 to 17416
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            17417 non-null  int64
 1   department             17417 non-null  object
 2   region                 17417 non-null  object
 3   education              16646 non-null  object
 4   gender                 17417 non-null  object
 5   recruitment_channel    17417 non-null  object
 6   no_of_trainings        17417 non-null  int64
 7   age                    17417 non-null  int64
 8   previous_year_rating   16054 non-null  float64
 9   length_of_service      17417 non-null  int64
 10  KPIs_met_more_than_80  17417 non-null  int64
 11  awards_won             17417 non-null  int64
 12  avg_training_score     17417 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 1.7+ MB

In [5]:
# null check
df.isnull().sum()

employee_id                 0
department                  0
region                      0
education                 771
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     1363
length_of_service           0
KPIs_met_more_than_80       0
awards_won                  0
avg_training_score          0
dtype: int64

In [16]:
# filling the null values of "education" feature with "Unknown"

df["education"] = df["education"].fillna("Unknown")

In [18]:
# checking if duplicates exists

df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
17412    False
17413    False
17414     True
17415     True
17416    False
Length: 17417, dtype: bool

In [19]:
# dropping the duplicates

df = df.drop_duplicates()

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17415 entries, 0 to 17416
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            17415 non-null  int64
 1   department             17415 non-null  object
 2   region                 17415 non-null  object
 3   education              17415 non-null  object
 4   gender                 17415 non-null  object
 5   recruitment_channel    17415 non-null  object
 6   no_of_trainings        17415 non-null  int64
 7   age                    17415 non-null  int64
 8   previous_year_rating   16052 non-null  float64
 9   length_of_service      17415 non-null  int64
 10  KPIs_met_more_than_80  17415 non-null  int64
 11  awards_won             17415 non-null  int64
 12  avg_training_score     17415 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 1.9+ MB

In [22]:
df.isnull().sum()

employee_id                 0
department                  0
region                      0
education                   0
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     1363
length_of_service           0
KPIs_met_more_than_80       0
awards_won                  0
avg_training_score          0
dtype: int64

In [23]:
df["gender"].unique()

array(['m', 'f'], dtype=object)

In [24]:
# gender mapping in gender column
gender_mapping = {"m" : "male", "f" : "female"}

df["gender"] = df["gender"].map(gender_mapping)

In [25]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
0,8724,Technology,region_26,Bachelors,male,sourcing,1,24,NaN,1,1,0,77
1,74430,HR,region_4,Bachelors,female,other,1,31,3.0,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelors,male,other,1,31,1.0,4,0,0,47
3,38562,Procurement,region_2,Bachelors,female,other,3,31,2.0,9,0,0,65
4,64486,Finance,region_29,Bachelors,male,sourcing,1,30,4.0,7,0,0,61

In [45]:
## feature engineering
## converting discrete age numbers into age brackets in a new feature "age_group".

bin_labels = ["Young adult", "Adult", "Middle-aged", "Senior citizen"]
bin_edges = [18,25,40,55,65]
df["age_group"] = pd.cut(df["age"], bins = bin_edges, labels = bin_labels)

In [46]:
df.sample(20)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score,age_group
1210,23890,Technology,region_22,Bachelors,male,other,1,31,4.0,3,1,0,81,Adult
12597,4090,Operations,region_2,Bachelors,male,sourcing,2,38,4.0,7,0,0,58,Adult
13957,44515,Technology,region_5,Bachelors,male,other,1,32,3.0,3,0,0,83,Adult
1477,22322,Operations,region_27,Bachelors,male,other,1,47,3.0,18,0,0,59,Middle-aged
9696,66409,Operations,region_27,Bachelors,female,other,1,29,3.0,2,0,0,62,Adult
8964,48625,Sales & Marketing,region_7,Masters & above,male,other,1,40,5.0,3,1,0,48,Adult
11554,13002,Analytics,region_29,Bachelors,male,sourcing,1,36,2.0,10,0,0,84,Adult
15720,25655,Sales & Marketing,region_7,Bachelors,male,other,1,37,3.0,8,0,0,46,Adult
6622,34508,HR,region_2,Bachelors,male,other,1,45,5.0,7,0,0,53,Middle-aged
11630,26576,Legal,region_2,Bachelors,male,sourcing,2,39,4.0,5,0,0,60,Adult
13139,64459,Procurement,region_13,Bachelors,male,other,2,29,3.0,3,1,0,72,Adult
6221,70719,Sales & Marketing,region_9,Bachelors,female,other,1,28,1.0,4,0,0,50,Adult
14106,59222,Technology,region_27,Bachelors,male,sourcing,1,28,NaN,1,1,0,80,Adult
12131,70562,Procurement,region_2,Bachelors,female,sourcing,1,39,4.0,5,1,0,73,Adult
17251,72957,Sales & Marketing,region_10,Masters & above,male,sourcing,1,41,4.0,6,1,1,90,Middle-aged
11750,14047,Technology,region_7,Bachelors,female,sourcing,1,31,4.0,3,0,0,82,Adult
13368,13483,Sales & Marketing,region_27,Unknown,male,other,1,25,4.0,1,1,0,53,Young adult
9118,2174,Sales & Marketing,region_12,Bachelors,male,sourcing,2,26,1.0,1,0,0,49,Adult
7850,21380,Sales & Marketing,region_17,Masters & above,male,other,1,40,5.0,10,0,0,49,Adult
16768,46021,Operations,region_30,Bachelors,male,sourcing,1,32,4.0,7,0,0,61,Adult

In [48]:
df.isnull().sum()

employee_id                 0
department                  0
region                      0
education                   0
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     1363
length_of_service           0
KPIs_met_more_than_80       0
awards_won                  0
avg_training_score          0
age_group                   0
dtype: int64

In [49]:
# filling the null values of "previous_year_rating" with the mode vale within their department 

df["previous_year_rating"] = df["previous_year_rating"].fillna(df.groupby("department")["previous_year_rating"].transform(lambda x : x.mode()[0]))

In [50]:
df.isnull().sum()

employee_id              0
department               0
region                   0
education                0
gender                   0
recruitment_channel      0
no_of_trainings          0
age                      0
previous_year_rating     0
length_of_service        0
KPIs_met_more_than_80    0
awards_won               0
avg_training_score       0
age_group                0
dtype: int64

In [51]:
# Renaming the column "KPIs_met_more_than_80" to lowercase and only characters 

df = df.rename(columns={"KPIs_met_more_than_80" : "kpis_met_more_than_eighty"})

In [52]:
df.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'kpis_met_more_than_eighty', 'awards_won',
       'avg_training_score', 'age_group'],
      dtype='object')

In [55]:
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,kpis_met_more_than_eighty,awards_won,avg_training_score,age_group
0,8724,Technology,region_26,Bachelors,male,sourcing,1,24,3.0,1,1,0,77,Young adult
1,74430,HR,region_4,Bachelors,female,other,1,31,3.0,5,0,0,51,Adult
2,72255,Sales & Marketing,region_13,Bachelors,male,other,1,31,1.0,4,0,0,47,Adult
3,38562,Procurement,region_2,Bachelors,female,other,3,31,2.0,9,0,0,65,Adult
4,64486,Finance,region_29,Bachelors,male,sourcing,1,30,4.0,7,0,0,61,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,57239,Sales & Marketing,region_31,Bachelors,male,other,1,42,3.0,10,0,0,53,Middle-aged
17411,73858,Sales & Marketing,region_25,Bachelors,male,sourcing,2,28,2.0,5,0,0,45,Adult
17412,64573,Technology,region_7,Bachelors,female,referred,2,30,5.0,6,1,0,81,Adult
17413,49584,HR,region_7,Bachelors,male,other,1,33,1.0,9,0,0,51,Adult
17416,64573,HR,region_7,Bachelors,female,referred,1,35,5.0,4,1,0,81,Adult

In [56]:
# feature engineering
# creating a new feature work experience from the feature length of service

bin_labels = ["Entry-level(0 to 2 yrs)", "Mid-level(3 to 7 yrs)", "Senior-level(7 to 12 yrs)", "Executive-level(12+ yrs)"]
bin_edges = [0,2,7,12,40]
df["work_experience"] = pd.cut(df["length_of_service"] , bins = bin_edges , labels = bin_labels)

In [58]:
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,kpis_met_more_than_eighty,awards_won,avg_training_score,age_group,work_experience
0,8724,Technology,region_26,Bachelors,male,sourcing,1,24,3.0,1,1,0,77,Young adult,Entry-level(0 to 2 yrs)
1,74430,HR,region_4,Bachelors,female,other,1,31,3.0,5,0,0,51,Adult,Mid-level(3 to 7 yrs)
2,72255,Sales & Marketing,region_13,Bachelors,male,other,1,31,1.0,4,0,0,47,Adult,Mid-level(3 to 7 yrs)
3,38562,Procurement,region_2,Bachelors,female,other,3,31,2.0,9,0,0,65,Adult,Senior-level(7 to 12 yrs)
4,64486,Finance,region_29,Bachelors,male,sourcing,1,30,4.0,7,0,0,61,Adult,Mid-level(3 to 7 yrs)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,57239,Sales & Marketing,region_31,Bachelors,male,other,1,42,3.0,10,0,0,53,Middle-aged,Senior-level(7 to 12 yrs)
17411,73858,Sales & Marketing,region_25,Bachelors,male,sourcing,2,28,2.0,5,0,0,45,Adult,Mid-level(3 to 7 yrs)
17412,64573,Technology,region_7,Bachelors,female,referred,2,30,5.0,6,1,0,81,Adult,Mid-level(3 to 7 yrs)
17413,49584,HR,region_7,Bachelors,male,other,1,33,1.0,9,0,0,51,Adult,Senior-level(7 to 12 yrs)
17416,64573,HR,region_7,Bachelors,female,referred,1,35,5.0,4,1,0,81,Adult,Mid-level(3 to 7 yrs)

In [65]:
# data frame to csv 

df.to_csv(r"C:\Users\HOME\Desktop\HR Analytics\HR_analytics_dataset.csv",index = False)